pipeline:
  name: MCS CD dv1
  identifier: mcs_cd
  projectIdentifier: loandepotmcs
  orgIdentifier: default
  tags:
    phase: "3"
    poc: "true"
  stages:
    - stage:
        name: Deploy dv1
        identifier: deploy_dv1
        type: Deployment
        spec:
          deploymentType: NativeHelm
          services:
            values:
              - serviceRef: mcs_core_service
                serviceInputs:
                  serviceDefinition:
                    type: NativeHelm
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              - serviceRef: mcs_public_service
                serviceInputs:
                  serviceDefinition:
                    type: NativeHelm
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              - serviceRef: mcs_textmessage_worker
                serviceInputs:
                  serviceDefinition:
                    type: NativeHelm
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
            metadata:
              parallel: true
          environment:
            environmentRef: dv1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dv1_infra
          execution:
            steps:
              - step:
                  name: Helm Deploy
                  identifier: helm_deploy
                  type: HelmDeploy
                  timeout: 15m
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                    useUpgradeInstall: true
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helm_rollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
