replicaCount: 1

image:
  repository: notify-public-api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80

containerPort: 8080

appEnvironment: local

logging:
  logLevel: Information

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  livenessPath: /health
  readinessPath: /health/ready
